SHELL_BUILDING=./make_log4cxx.sh

all:
	$(SHELL_BUILDING); cd ./slog; cmake .;make;

clean:
	rm -rf ./log4cxx/apache* ./log4cxx/include ./log4cxx/lib ./slog/include ./slog/lib ./slog/CMakeCache.txt ./slog/CMakeFiles ./slog/Makefile ./slog/*.so ./slog/cmake_install.cmake
