module("four_miles_conf",package.seeall)
POI_LIST ={
	[1045] = {
		["time_conf"] = "0",
		["receiver_dis"] = 150,
		["txt"] = "易滑",
		["issued_Type"] = "1",
		["context"] = "易滑路段，天气不好，需更加小心。",
		["dis"] = 500,
		["random_numbers"] = 4,
		["interval"] = 30,
	},
	[1245] = {
		["time_conf"] = "0",
		["receiver_dis"] = 500,
		["txt"] = "高架易滑",
		["issued_Type"] = "1",
		["context"] = "易滑路段，天气不好，需更加小心。",
		["dis"] = 800,
		["random_numbers"] = 4,
		["interval"] = 30,
	},
	[1145] = {
		["time_conf"] = "0",
		["receiver_dis"] = 1000,
		["txt"] = "高速易滑",
		["issued_Type"] = "1",
		["context"] = "易滑路段，天气不好，需更加小心。",
		["dis"] = 1500,
		["random_numbers"] = 4,
		["interval"] = 30,
	},
	[1044] = {
		["time_conf"] = "0",
		["receiver_dis"] = 150,
		["txt"] = "事故易发地段",
		["issued_Type"] = "1",
		["context"] = "事故易发地段，请缓行。",
		["dis"] = 500,
		["random_numbers"] = 6,
		["interval"] = 30,
	},
	[1071] = {
		["time_conf"] = "0",
		["receiver_dis"] = 150,
		["txt"] = "连续弯路",
		["issued_Type"] = "1",
		["context"] = "前方有连续急转弯，请降低车速，小心通行。",
		["dis"] = 500,
		["random_numbers"] = 2,
		["interval"] = 30,
	},
	[1271] = {
		["time_conf"] = "0",
		["receiver_dis"] = 500,
		["txt"] = "高架连续弯路",
		["issued_Type"] = "1",
		["context"] = "前方有连续急转弯，请降低车速，小心通行。",
		["dis"] = 1000,
		["random_numbers"] = 2,
		["interval"] = 30,
	},
	[1227] = {
		["time_conf"] = "0",
		["receiver_dis"] = 500,
		["txt"] = "高架隧道",
		["issued_Type"] = "1",
		["context"] = "高架隧道",
		["dis"] = 1000,
		["random_numbers"] = 7,
		["interval"] = 30,
	},
	[1244] = {
		["time_conf"] = "0",
		["receiver_dis"] = 500,
		["txt"] = "高架事故易发地段",
		["issued_Type"] = "1",
		["context"] = "高架事故易发地段",
		["dis"] = 1000,
		["random_numbers"] = 6,
		["interval"] = 30,
	},
	[1230] = {
		["time_conf"] = "0",
		["receiver_dis"] = 500,
		["txt"] = "高架大桥",
		["issued_Type"] = "1",
		["context"] = "高架大桥",
		["dis"] = 1000,
		["random_numbers"] = 2,
		["interval"] = 30,
	},
	[1171] = {
		["time_conf"] = "0",
		["receiver_dis"] = 500,
		["txt"] = "高速连续弯路",
		["issued_Type"] = "1",
		["context"] = "前方有连续急转弯，请降低车速，小心通行。",
		["dis"] = 1000,
		["random_numbers"] = 2,
		["interval"] = 30,
	},
	[1144] = {
		["time_conf"] = "0",
		["receiver_dis"] = 1000,
		["txt"] = "高速事故易发地段",
		["issued_Type"] = "1",
		["context"] = "高速事故易发地段",
		["dis"] = 1500,
		["random_numbers"] = 6,
		["interval"] = 30,
	},
	[1127] = {
		["time_conf"] = "0",
		["receiver_dis"] = 1000,
		["txt"] = "高速隧道",
		["issued_Type"] = "1",
		["context"] = "高速隧道",
		["dis"] = 1500,
		["random_numbers"] = 7,
		["interval"] = 30,
	},
	[1130] = {
		["time_conf"] = "0",
		["receiver_dis"] = 500,
		["txt"] = "高速大桥",
		["issued_Type"] = "1",
		["context"] = "高速大桥",
		["dis"] = 1000,
		["random_numbers"] = 2,
		["interval"] = 30,
	},
	[1010] = {
		["receiver_dis"] = 150,
		["issued_Type"] = "1",
		["hour"] = {
			[2] = {
				["hour2"] = 23,
				["hour1"] = 18,
			},
			[1] = {
				["hour2"] = 9,
				["hour1"] = 0,
			},
		},
		["random_numbers"] = 6,
		["context"] = "动物园",
		["time_conf"] = "1",
		["dis"] = 500,
		["txt"] = "动物园",
		["interval"] = 30,
	},
	[1048] = {
		["time_conf"] = "0",
		["receiver_dis"] = 150,
		["txt"] = "无人看管的铁路道口",
		["issued_Type"] = "1",
		["context"] = "前方为铁路道口，请谨慎驾驶。",
		["dis"] = 500,
		["random_numbers"] = 3,
		["interval"] = 30,
	},
	[1049] = {
		["time_conf"] = "0",
		["receiver_dis"] = 200,
		["txt"] = "反向弯路",
		["issued_Type"] = "1",
		["context"] = "反向弯路",
		["dis"] = 500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[1249] = {
		["time_conf"] = "0",
		["receiver_dis"] = 800,
		["txt"] = "高架反向弯路",
		["issued_Type"] = "1",
		["context"] = "高架反向弯路",
		["dis"] = 1200,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[1149] = {
		["time_conf"] = "0",
		["receiver_dis"] = 100,
		["txt"] = "高速反向道路",
		["issued_Type"] = "1",
		["context"] = "高速反向道路",
		["dis"] = 1500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[1065] = {
		["receiver_dis"] = 300,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "火车站 poiid",
		["txt"] = "火车站",
		["dir"] = 30,
		["dis"] = 500,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1020] = {
		["receiver_dis"] = 100,
		["issued_Type"] = "1",
		["hour"] = {
			[1] = {
				["hour2"] = 6,
				["hour1"] = 0,
			},
			[2] = {
				["hour2"] = 16,
				["hour1"] = 8,
			},
			[3] = {
				["hour2"] = 23,
				["hour1"] = 17,
			},
		},
		["random_numbers"] = 5,
		["context"] = "前方是小学",
		["time_conf"] = "1",
		["week"] = {
			[1] = {
				["week1"] = 6,
				["week2"] = 7,
			},
		},
		["month"] = {
			[1] = {
				["month1"] = 7,
				["month2"] = 8,
			},
		},
		["dis"] = 500,
		["txt"] = "小学",
		["interval"] = 30,
	},
	[1066] = {
		["receiver_dis"] = 300,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "客运站 POIID",
		["txt"] = "客运站",
		["dir"] = 30,
		["dis"] = 500,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1064] = {
		["receiver_dis"] = 300,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "飞机场 POIID",
		["txt"] = "飞机场",
		["dir"] = 30,
		["dis"] = 500,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1019] = {
		["receiver_dis"] = 100,
		["issued_Type"] = "1",
		["hour"] = {
			[4] = {
				["hour2"] = 23,
				["hour1"] = 18,
			},
			[1] = {
				["hour2"] = 6,
				["hour1"] = 0,
			},
			[2] = {
				["hour2"] = 12,
				["hour1"] = 8,
			},
			[3] = {
				["hour2"] = 17,
				["hour1"] = 13,
			},
		},
		["random_numbers"] = 5,
		["context"] = "前方是中学",
		["time_conf"] = "1",
		["week"] = {
			[1] = {
				["week1"] = 6,
				["week2"] = 7,
			},
		},
		["month"] = {
			[1] = {
				["month1"] = 7,
				["month2"] = 8,
			},
		},
		["dis"] = 500,
		["txt"] = "中学",
		["interval"] = 30,
	},
	[1046] = {
		["time_conf"] = "0",
		["receiver_dis"] = 150,
		["txt"] = "村庄",
		["issued_Type"] = "1",
		["context"] = "经过村庄路段，小心岔路来车。",
		["dis"] = 500,
		["random_numbers"] = 3,
		["interval"] = 30,
	},
	[1024] = {
		["receiver_dis"] = 300,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "博物馆，poiid",
		["txt"] = "博物馆",
		["dir"] = 30,
		["dis"] = 500,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1050] = {
		["time_conf"] = "0",
		["receiver_dis"] = 200,
		["txt"] = "左侧合流",
		["issued_Type"] = "1",
		["context"] = "请注意并线车辆，小心驾驶注意避让。",
		["dis"] = 500,
		["random_numbers"] = 2,
		["interval"] = 30,
	},
	[1250] = {
		["time_conf"] = "0",
		["receiver_dis"] = 500,
		["txt"] = "高架左侧合流",
		["issued_Type"] = "1",
		["context"] = "请注意并线车辆，小心驾驶注意避让。",
		["dis"] = 800,
		["random_numbers"] = 2,
		["interval"] = 30,
	},
	[1251] = {
		["time_conf"] = "0",
		["receiver_dis"] = 500,
		["txt"] = "高架右侧合流",
		["issued_Type"] = "1",
		["context"] = "请注意并线车辆，小心驾驶注意避让。",
		["dis"] = 800,
		["random_numbers"] = 2,
		["interval"] = 30,
	},
	[1151] = {
		["time_conf"] = "0",
		["receiver_dis"] = 1000,
		["txt"] = "高速右侧合流",
		["issued_Type"] = "1",
		["context"] = "请注意并线车辆，小心驾驶注意避让。",
		["dis"] = 1500,
		["random_numbers"] = 2,
		["interval"] = 30,
	},
	[1150] = {
		["time_conf"] = "0",
		["receiver_dis"] = 1000,
		["txt"] = "高速左侧合流",
		["issued_Type"] = "1",
		["context"] = "请注意并线车辆，小心驾驶注意避让。",
		["dis"] = 1500,
		["random_numbers"] = 2,
		["interval"] = 30,
	},
	[1027] = {
		["receiver_dis"] = 300,
		["issued_Type"] = "1",
		["hour"] = {
			[2] = {
				["hour2"] = 23,
				["hour1"] = 19,
			},
			[1] = {
				["hour2"] = 7,
				["hour1"] = 0,
			},
		},
		["random_numbers"] = 7,
		["context"] = "即将进入隧道",
		["time_conf"] = "1",
		["dis"] = 600,
		["txt"] = "隧道",
		["interval"] = 30,
	},
	[1043] = {
		["receiver_dis"] = 200,
		["issued_Type"] = "1",
		["hour"] = {
			[2] = {
				["hour2"] = 23,
				["hour1"] = 18,
			},
			[1] = {
				["hour2"] = 6,
				["hour1"] = 0,
			},
		},
		["random_numbers"] = 0,
		["context"] = "儿童出入位置",
		["time_conf"] = "1",
		["dis"] = 500,
		["txt"] = "儿童出入位置",
		["interval"] = 30,
	},
	[1009] = {
		["time_conf"] = "0",
		["receiver_dis"] = 200,
		["txt"] = "旅游景点",
		["issued_Type"] = "1",
		["context"] = "旅游景点 poiid",
		["dis"] = 500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[1081] = {
		["time_conf"] = "0",
		["receiver_dis"] = 200,
		["txt"] = "立交",
		["issued_Type"] = "1",
		["context"] = "立交 poiid",
		["dis"] = 500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[1008] = {
		["receiver_dis"] = 300,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "特殊酒店 poiid",
		["txt"] = "特殊酒店",
		["dir"] = 30,
		["dis"] = 500,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1025] = {
		["receiver_dis"] = 300,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "图书馆 poiid",
		["txt"] = "图书馆",
		["dir"] = 30,
		["dis"] = 500,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1135] = {
		["level"] = 30,
		["receiver_dis"] = 300,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "高速出口收费站 poiid",
		["txt"] = "高速出口收费站",
		["dis"] = 800,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1192] = {
		["level"] = 30,
		["receiver_dis"] = 500,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "高速出口 poiid",
		["txt"] = "高速出口",
		["dis"] = 800,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1030] = {
		["time_conf"] = "0",
		["receiver_dis"] = 200,
		["txt"] = "大桥",
		["issued_Type"] = "1",
		["context"] = "正在经过大桥",
		["dis"] = 500,
		["random_numbers"] = 2,
		["interval"] = 30,
	},
	[1036] = {
		["receiver_dis"] = 300,
		["issued_Type"] = "1",
		["hour"] = {
			[2] = {
				["hour2"] = 23,
				["hour1"] = 19,
			},
			[1] = {
				["hour2"] = 9,
				["hour1"] = 0,
			},
		},
		["random_numbers"] = 0,
		["context"] = "有名大桥 poiid",
		["txt"] = "有名大桥",
		["dir"] = 30,
		["dis"] = 500,
		["time_conf"] = "1",
		["interval"] = 30,
	},
	[1236] = {
		["receiver_dis"] = 500,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "高架有名大桥 poiid",
		["txt"] = "高架有名大桥",
		["dir"] = 30,
		["dis"] = 1000,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1292] = {
		["receiver_dis"] = 500,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "高架出口 poiid",
		["txt"] = "高架出口",
		["dir"] = 30,
		["dis"] = 1000,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1136] = {
		["receiver_dis"] = 1000,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "高速有名大桥 poiid",
		["txt"] = "高速有名大桥",
		["dir"] = 30,
		["dis"] = 1500,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1067] = {
		["receiver_dis"] = 300,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "港口码头 poiid",
		["txt"] = "港口码头",
		["dir"] = 30,
		["dis"] = 500,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1033] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 200,
		["txt"] = "违章摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有违章摄像头",
		["dis"] = 500,
		["random_numbers"] = 3,
		["interval"] = 30,
	},
	[1233] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 500,
		["txt"] = "高架违章摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有违章摄像头",
		["dis"] = 800,
		["random_numbers"] = 3,
		["interval"] = 30,
	},
	[1133] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 1000,
		["txt"] = "高速违章摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有违章摄像头",
		["dis"] = 1500,
		["random_numbers"] = 3,
		["interval"] = 30,
	},
	[1016] = {
		["receiver_dis"] = 300,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "公园 poiid",
		["txt"] = "公园",
		["dir"] = 30,
		["dis"] = 500,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1190] = {
		["level"] = 21,
		["receiver_dis"] = 1000,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "服务区 poiid",
		["txt"] = "服务区",
		["dis"] = 1500,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1191] = {
		["level"] = 21,
		["receiver_dis"] = 1000,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "高速停车区 poiid",
		["txt"] = "高速停车区",
		["dis"] = 1500,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1026] = {
		["time_conf"] = "0",
		["receiver_dis"] = 200,
		["txt"] = "大学城",
		["issued_Type"] = "1",
		["context"] = "大学城",
		["dis"] = 500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[1028] = {
		["time_conf"] = "0",
		["receiver_dis"] = 200,
		["txt"] = "环岛",
		["issued_Type"] = "1",
		["context"] = "环岛",
		["dis"] = 500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[1003] = {
		["receiver_dis"] = 300,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "大型体育馆 poiid",
		["txt"] = "大型体育馆",
		["dir"] = 30,
		["dis"] = 500,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1002] = {
		["receiver_dis"] = 100,
		["issued_Type"] = "1",
		["hour"] = {
			[2] = {
				["hour2"] = 23,
				["hour1"] = 18,
			},
			[1] = {
				["hour2"] = 7,
				["hour1"] = 0,
			},
		},
		["random_numbers"] = 5,
		["context"] = "农贸市场路段，请缓行",
		["time_conf"] = "1",
		["dis"] = 500,
		["txt"] = "农贸市场",
		["interval"] = 15,
	},
	[112311035] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 200,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速35",
		["dis"] = 500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[1021] = {
		["receiver_dis"] = 100,
		["issued_Type"] = "1",
		["hour"] = {
			[1] = {
				["hour2"] = 6,
				["hour1"] = 0,
			},
			[2] = {
				["hour2"] = 15,
				["hour1"] = 8,
			},
			[3] = {
				["hour2"] = 23,
				["hour1"] = 17,
			},
		},
		["random_numbers"] = 5,
		["context"] = "前方是幼儿园",
		["time_conf"] = "1",
		["week"] = {
			[1] = {
				["week1"] = 6,
				["week2"] = 7,
			},
		},
		["month"] = {
			[1] = {
				["month1"] = 7,
				["month2"] = 8,
			},
		},
		["dis"] = 500,
		["txt"] = "幼儿园",
		["interval"] = 30,
	},
	[1018] = {
		["receiver_dis"] = 300,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "大学 poiid",
		["txt"] = "大学",
		["dir"] = 30,
		["dis"] = 500,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1042] = {
		["time_conf"] = "0",
		["receiver_dis"] = 200,
		["txt"] = "道路中间人行横道",
		["issued_Type"] = "1",
		["context"] = "道路中间人行道",
		["dis"] = 500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[1051] = {
		["time_conf"] = "0",
		["receiver_dis"] = 200,
		["txt"] = "右侧合流",
		["issued_Type"] = "1",
		["context"] = "请注意并线车辆，小心驾驶注意避让。",
		["dis"] = 500,
		["random_numbers"] = 2,
		["interval"] = 30,
	},
	[1022] = {
		["receiver_dis"] = 300,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "展览馆 poiid",
		["txt"] = "展览馆",
		["dir"] = 30,
		["dis"] = 500,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1072] = {
		["time_conf"] = "0",
		["receiver_dis"] = 150,
		["txt"] = "注意落石 右侧",
		["issued_Type"] = "1",
		["context"] = "该路段有落石风险，请小心驾驶。",
		["dis"] = 500,
		["random_numbers"] = 2,
		["interval"] = 30,
	},
	[1073] = {
		["time_conf"] = "0",
		["receiver_dis"] = 150,
		["txt"] = "注意落石 左侧",
		["issued_Type"] = "1",
		["context"] = "该路段有落石风险，请小心驾驶。",
		["dis"] = 500,
		["random_numbers"] = 2,
		["interval"] = 30,
	},
	[1173] = {
		["time_conf"] = "0",
		["receiver_dis"] = 1000,
		["txt"] = "高速注意落石 左侧",
		["issued_Type"] = "1",
		["context"] = "该路段有落石风险，请小心驾驶。",
		["dis"] = 1500,
		["random_numbers"] = 2,
		["interval"] = 30,
	},
	[1172] = {
		["time_conf"] = "0",
		["receiver_dis"] = 1000,
		["txt"] = "高速注意落石 右侧",
		["issued_Type"] = "1",
		["context"] = "该路段有落石风险，请小心驾驶。",
		["dis"] = 1500,
		["random_numbers"] = 2,
		["interval"] = 30,
	},
	[1023] = {
		["time_conf"] = "0",
		["receiver_dis"] = 150,
		["txt"] = "驾校",
		["issued_Type"] = "1",
		["context"] = "附近有驾校，请注意马路杀手",
		["dis"] = 500,
		["random_numbers"] = 9,
		["interval"] = 30,
	},
	[1070] = {
		["time_conf"] = "0",
		["receiver_dis"] = 150,
		["txt"] = "急弯路",
		["issued_Type"] = "1",
		["context"] = "急转弯",
		["dis"] = 500,
		["random_numbers"] = 3,
		["interval"] = 30,
	},
	[1270] = {
		["time_conf"] = "0",
		["receiver_dis"] = 500,
		["txt"] = "高架急弯路",
		["issued_Type"] = "1",
		["context"] = "高架急转弯",
		["dis"] = 800,
		["random_numbers"] = 3,
		["interval"] = 30,
	},
	[1170] = {
		["time_conf"] = "0",
		["receiver_dis"] = 1000,
		["txt"] = "高速急弯路",
		["issued_Type"] = "1",
		["context"] = "高速急转弯",
		["dis"] = 1500,
		["random_numbers"] = 3,
		["interval"] = 30,
	},
	[1047] = {
		["time_conf"] = "0",
		["receiver_dis"] = 150,
		["txt"] = "有人看管的铁路道口",
		["issued_Type"] = "1",
		["context"] = "前方为铁路道口，请谨慎驾驶。",
		["dis"] = 500,
		["random_numbers"] = 3,
		["interval"] = 30,
	},
	[1011] = {
		["receiver_dis"] = 150,
		["issued_Type"] = "1",
		["hour"] = {
			[2] = {
				["hour2"] = 23,
				["hour1"] = 18,
			},
			[1] = {
				["hour2"] = 0,
				["hour1"] = 0,
			},
		},
		["random_numbers"] = 6,
		["context"] = "植物园",
		["time_conf"] = "1",
		["dis"] = 500,
		["txt"] = "植物园",
		["interval"] = 30,
	},
	[1134] = {
		["level"] = 30,
		["receiver_dis"] = 1000,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "高速跨省收费站 poiid",
		["txt"] = "高速跨省收费站",
		["dis"] = 2000,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1031] = {
		["level"] = 30,
		["receiver_dis"] = 200,
		["issued_Type"] = "1",
		["random_numbers"] = 0,
		["context"] = "非高速收费站 poiid",
		["txt"] = "非高速收费站",
		["dis"] = 5000,
		["time_conf"] = "0",
		["interval"] = 30,
	},
	[1029] = {
		["time_conf"] = "0",
		["receiver_dis"] = 200,
		["txt"] = "加油站",
		["issued_Type"] = "1",
		["context"] = "马上会经过一个加油站，请检查油表油量",
		["dis"] = 500,
		["random_numbers"] = 3,
		["interval"] = 30,
	},
	[1129] = {
		["time_conf"] = "0",
		["receiver_dis"] = 1000,
		["txt"] = "高速加油站",
		["issued_Type"] = "1",
		["context"] = "马上会经过一个加油站，请检查油表油量",
		["dis"] = 1500,
		["random_numbers"] = 3,
		["interval"] = 30,
	},
	[1032] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 200,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[103230] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 200,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[103235] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 200,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[103240] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 200,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[103245] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 200,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[103250] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 200,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[103255] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 200,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[103260] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 200,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[103270] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 200,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[103280] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 200,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[103290] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 200,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[1032100] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 200,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[113260] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 1000,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 1500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[113270] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 1000,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 1500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[113280] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 1000,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 1500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[113290] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 1000,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 1500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[1132100] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 1000,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 1500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[1132110] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 500,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 1500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[1132120] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 1000,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 1500,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[1232] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 500,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 800,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[123230] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 500,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 800,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[123235] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 500,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 800,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[123240] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 500,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 800,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[123245] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 500,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 800,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[123250] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 500,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 800,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[123255] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 500,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 800,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[123260] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 500,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 800,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[123270] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 500,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 800,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[123280] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 500,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 800,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[123290] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 500,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 800,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[1232100] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 500,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 800,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[1232110] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 500,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 800,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
	[1232120] = {
		["time_conf"] = "0",
		["level"] = 25,
		["receiver_dis"] = 500,
		["txt"] = "限速摄像头",
		["issued_Type"] = "2",
		["context"] = "前方有限速摄像头,限速30",
		["dis"] = 800,
		["random_numbers"] = 0,
		["interval"] = 30,
	},
}
