module("BYNAME_LIST")


OWN_LIST = {
        [ "/msgsearchapi/getsendmessage" ]              = "getsendmessage",
        [ "/msgsearchapi/getgeotomessage" ]             = "getgeotomessage",
        [ "/msgsearchapi/getvoices" ]                   = "getvoices",
        [ "/msgsearchapi/getreplyvoices" ]              = "getreplyvoices",
        [ "/msgsearchapi/getsendbizid" ]                = "getsendbizid",
        [ "/msgsearchapi/getsendinfo" ]                 = "getsendinfo",
        [ "/msgsearchapi/getvoice" ]                    = "getvoice",
        [ "/msgsearchapi/getreplyvoice" ]               = "getreplyvoice",
        [ "/msgsearchapi/getfilelocation" ]             = "getfilelocation",
        [ "/msgsearchapi/getgeobizid" ]                 = "getgeobizid",
        [ "/msgsearchapi/getsendbizidsize" ]            = "getsendbizidsize",
        [ "/msgsearchapi/getgeobizidsize" ]             = "getgeobizidsize",
        [ "/msgsearchapi/getvoicesize" ]                = "getvoicesize",
        [ "/msgsearchapi/getfeedbackinfo" ]             = "getfeedbackinfo",
        [ "/msgsearchapi/getfeedbackinfos" ]            = "getfeedbackinfos",
        [ "/msgsearchapi/getfeedbackinfosize" ]         = "getfeedbackinfosize",
        [ "/msgsearchapi/getnewstatusinfo" ]            = "getnewstatusinfo",
        [ "/msgsearchapi/getreadmessageinfo" ]          = "getreadmessageinfo",
        [ "/msgsearchapi/getreadmessage" ]              = "getreadmessage",
        [ "/msgsearchapi/getreadmessages" ]             = "getreadmessages",
        [ "/msgsearchapi/getreadmessagesize" ]          = "getreadmessagesize",
        [ "/msgsearchapi/getreleaseadtalk" ]            = "getreleaseadtalk",
        [ "/msgsearchapi/getreleaseadtalks" ]           = "getreleaseadtalks",
        [ "/msgsearchapi/getreleaseadtalksize" ]        = "getreleaseadtalksize",
        [ "/msgsearchapi/getreleasemessageinfo" ]       = "getreleasemessageinfo",
        [ "/msgsearchapi/getreleasemessage" ]           = "getreleasemessage",
        [ "/msgsearchapi/getreleasemessages" ]          = "getreleasemessages",
        [ "/msgsearchapi/getreleasemessagesize" ]       = "getreleasemessagesize",
        [ "/msgsearchapi/getcitymessage" ]              = "getcitymessage",
        [ "/msgsearchapi/getcitymessageinfo" ]          = "getcitymessageinfo",
        [ "/msgsearchapi/getcitycode" ]                 = "getcitycode",
        [ "/msgsearchapi/getcitycodemessage" ]          = "getcitycodemessage",
        [ "/msgsearchapi/getcitycodevoice" ]            = "getcitycodevoice",
}
