module("STATUS_LIST")


OWN_LIST = {
        {"getsendmessage",              "open"},
        {"getgeotomessage",             "open"},
        {"getvoices",                   "open"},
        {"getreplyvoices",              "open"},
        {"getsendbizid",                "open"},
        {"getsendinfo",                 "open"},
        {"getvoice",                    "open"},
        {"getreplyvoice",               "open"},
        {"getfilelocation",             "open"},
        {"getgeobizid",                 "open"},
        {"getsendbizidsize",            "open"},
        {"getgeobizidsize",             "open"},
        {"getvoicesize",                "open"},
        {"getfeedbackinfo",             "open"},
        {"getfeedbackinfos",            "open"},
        {"getfeedbackinfosize",         "open"},
        {"getnewstatusinfo",            "open"},
        {"getreadmessageinfo",          "open"},
        {"getreadmessage",              "open"},
        {"getreadmessages",             "open"},
        {"getreadmessagesize",          "open"},
        {"getreleaseadtalk",            "open"},
        {"getreleaseadtalks",           "open"},
        {"getreleaseadtalksize",        "open"},
        {"getreleasemessageinfo",       "open"},
        {"getreleasemessage",           "open"},
        {"getreleasemessages",          "open"},
        {"getreleasemessagesize",       "open"},
        {"getcitymessage",              "open"},
        {"getcitymessageinfo",          "open"},
        {"getcitycode",                 "open"},
        {"getcitycodemessage",          "open"},
        {"getcitycodevoice",            "open"},
}
