local apis = {

	-->	julieZheng	
	insertTraffic =			"julieZheng",
	getTraffic =			"julieZheng",
	sendWeibo =			"julieZheng",
	sendWeiboOnline =		"julieZheng",
	setUserSubscribedRoad =		"julieZheng",
	getUserSubscribedRoad =		"julieZheng",
	getDaokeCount =			"julieZheng",
	getMedalList =			"julieZheng",
	getUserMedal =			"julieZheng",
	getOnlineCount =		"julieZheng",
	getUserOnlineTime =		"julieZheng",
	getUserMileage =		"julieZheng",
	getVerificationCode =		"julieZheng",
	daokePassby =			"julieZheng",
	addTopic =			"julieZheng",
	getTopic =			"julieZheng",
	updateTopic =			"julieZheng",
	addDiscussTopic =		"julieZheng",
	updateDiscussTopic =		"julieZheng",
	statisticSharedWeibo =		"julieZheng",
	api_mp3_to_voice    =           "julieZheng",
	-->	zhangjl
	getIDByAnotherID =		"zhangjl",
	daokePoints =			"zhangjl",
	getPoints =			"zhangjl",
	remindPoints =			"zhangjl",
	consumePoints =			"zhangjl",
	addSubscribedWeiboType =	"zhangjl",
	addAdtalk =			"zhangjl",
	deleteAdtalk =			"zhangjl",
	pushMessage =			"zhangjl",
	pushMessageNotification =	"zhangjl",
	getMedalStatistic =		"zhangjl",
	addAccount =			"zhangjl",
	disconnectAccount =		"zhangjl",
	sendVerificationURL =		"zhangjl",
	updateUserid =			"zhangjl",
	correctLonLat =			"zhangjl",
	getDiscussion =			"zhangjl",
	-->	baoxue
	session =			"baoxue",
	getTspBizid =			"baoxue",
	sinaSendWeibo =			"baoxue",
	sinaSaveOauth =			"baoxue",
	sinaCheckOauth =		"baoxue",
	userBindAccountMirrtalk =	"baoxue",
	saveSound =			"baoxue",
	getSound =			"baoxue",
	setDaokelogsrelayPid =		"baoxue",
	getAllSubscribedWeiboType =	"baoxue",
	getUserSubscribedWeiboType =	"baoxue",
	getUserUnsubscribedWeiboType =	"baoxue",
	updateUserSubscribedWeiboType =	"baoxue",
	addMirrtalkSubscribedWeiboType ="baoxue",
}

return apis
