#ifndef __ERROR_H__
#define __ERROR_H__

enum errors
{
	API_OK,
	API_FAILED,
	API_ERR_BASE,
	API_WEIBO_EXPIRE,

	API_NO_MEMORY,
	API_NO_DATA,
	API_DATA_TOO_LONG,
	API_INVALID_JSON,
	API_INVALID_APPKEY,
	API_INVALID_MULTIMEDIAURL,
	API_INVALID_ENDTIME,
	API_INVALID_SOURCEID,
	API_INVALID_COMMENTID,
	API_INVALID_MESSAGETYPE,
	API_INVALID_SENDERTYPE,
	API_INVALID_CONTENT,
	API_INVALID_GEOMETRYTYPE,
	API_INVALID_RECEIVERLONGITUDE,
	API_INVALID_RECEIVERLATITUDE,
	API_INVALID_RECEIVERDISTANCE,
	API_INVALID_RECEIVERDIRECTION,
	API_INVALID_RECEIVERSPEED,
	API_INVALID_INVALIDDIS,
	API_INVALID_BIZID,
	API_INVALID_INTERVAL,
	API_INVALID_LEVEL,
	API_INVALID_RECEIVERACCOUNTID,
	API_INVALID_SENDERACCOUNTID,
	API_INVALID_TIPTYPE,
	API_INVALID_CALLBACKURL,
	API_INVALID_APPLYCALLBACKURL,
	API_INVALID_APPENDFILEURL,
	API_INVALID_AUTOREPLY,
	API_INVALID_POIID,
	API_INVALID_POITYPE,
	API_INVALID_GROUPID,
	API_INVALID_REGIONCODE,
	API_INVALID_RECEIVESELF,
	API_INVALID_ISONLINE,
	API_INVALID_ISCHANNEL,
	API_INVALID_RECEIVECROWD,

	JSON_OP_FAIL,
	HTTP_OP_FAIL,
	REDIS_OP_FAIL,

	REDIS_POOL_GAIN_FAILED,
	HTTP_POOL_GAIN_FAILED,

	API_ERR_OVER,
};

char *handle_error(int err);
#endif	/* ifndef __ERROR_H__ */

